name: Cleanup - Pull Request Closing
run-name: Cleanup Environment after closed Pull Request for Branch ${{ inputs.branch-name}} triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
      branch-name:
        required: true
        type: string
jobs:
  determine-cluster-name:
    runs-on: ubuntu-latest
    outputs:
      cluster-name-not-normalised: ${{ steps.calculateClusterName.outputs.cluster_name_not_normalised }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: calculateClusterName
        shell: bash
        run: |
          if test -f "day_over.txt"; then
            echo "cluster_name_not_normalised=fsmakka-gke-dev-day-over" >> "$GITHUB_OUTPUT"
          else
            echo "cluster_name_not_normalised=fsmakka-gke-dev" >> "$GITHUB_OUTPUT"
          fi
  cleanup-environment:
    needs: determine-cluster-name
    uses: ./.github/workflows/cleanup-environment.yaml
    with:
      branch-name: ${{ inputs.branch-name }}-${{ inputs.repo-name }}
      cluster-name-not-normalised: ${{ needs.determine-cluster-name.outputs.cluster-name-not-normalised }}
    secrets: inherit
  cleanup-umbrella-chart:
    runs-on: ubuntu-latest
    needs: cleanup-environment
    steps:
      - name: Clean Umbrella Helm Chart
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: 'delete-branch-with-reuse.yaml'
          repo: 'mehmetsalgar/fsm-akka-helm-umbrella-chart'
          ref: 'master'
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 10m
          wait-for-completion-interval: 10s
          inputs: '{"branch-name": "${{ inputs.branch-name }}-${{ inputs.repo-name }}"}'
