name: Create Branch
run-name: ${{ github.actor }}
on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
      base-branch-name:
        required: true
        type: string
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ inputs.base-branch-name }}"
          fetch-depth: 0
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          branch: 'refs/heads/${{ inputs.branch-name }}'