name: Create Service Environment in Kubernetes
run-name: Create Service Environments in Kubernetes triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
      base-branch-name:
        required: true
        type: string
      cluster-name:
        type: string
        required: true
      cluster-name-not-normalised:
        type: string
        required: true
jobs:
  create-services-environment-in-k8s:
    name: Create Services Environment in K8s with Branch Name as Namespace
    runs-on: ubuntu-latest
    steps:
      - name: Create Future Environment in K8s
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: 'build-service-environment-with-reuse.yaml'
          repo: 'mehmetsalgar/fsm-akka-4eyes-argocd'
          ref: "${{ inputs.base-branch-name }}"
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 5m
          wait-for-completion-interval: 10s
          inputs: '{"branch-name": "${{ inputs.branch-name }}", "cluster-name": "${{ inputs.cluster-name }}", "cluster-name-not-normalised": "${{ inputs.cluster-name-not-normalised }}"}'
