name: Create Infrastructure in Kubernetes
run-name: Creating Infrastructure in Kubernetes triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
      base-branch-name:
        required: true
        type: string
      value-file:
        required: true
        type: string
      cluster-name-not-normalised:
        type: string
        required: true
jobs:
  create-infrastructure-in-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Create Future Infrastructure Environment in K8s
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: 'build-infrastructure-environment-with-reuse.yaml'
          repo: 'mehmetsalgar/fsm-akka-helm-infrastructure-chart'
          ref: "${{ inputs.base-branch-name }}"
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 5m
          wait-for-completion-interval: 10s
          inputs: '{"branch-name": "${{ inputs.branch-name }}", "value-file": "${{ inputs.value-file }}", "cluster-name-not-normalised": "${{ inputs.cluster-name-not-normalised }}"}'