name: Delete Branch
run-name: ${{ github.actor }}
on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branches: ${{ inputs.branch-name }}