name: Helm Install
run-name: Installing to Helm triggered via ${{ github.event_name }} by ${{ github.actor }} ${{ github.actor }}
on:
  workflow_call:
    inputs:
      helm-command:
        required: true
        type: string
jobs:
  build-environment-for-future-branch:
    runs-on: ubuntu-latest
    steps:
      - id: install-kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'
      #  - id: kubectl-set-context
      #    uses: azure/k8s-set-context@v1
      #    with:
      #      method: kubeconfig
      #      kubeconfig: ''
      #      context: 'k3d-poc-akka'
      #      - name: Run Kubectl Command
      #        run: |
      #          kubectl version
      - id: install
        uses: azure/setup-helm@v3
        with:
          version: '3.10.3'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Helm Command
        id: helmCommand
        run: |
          cd helm
          #helm repo add fsm-akka http://fsmakka.salgar.org/repository/fsm-akka-helm/
          #helm repo update
          helm version          
          echo '${{ inputs.helm-command }}'
      - name: Check Failure
        if: steps.helmCommand.outcome != 'success'
        run: exit 1